#!/bin/bash
#SBATCH --job-name=strong_scaling_stencil
#SBATCH --array=0-5                    # 6 jobs
#SBATCH --ntasks-per-node=1            # 1 MPI task per node
#SBATCH --cpus-per-task=112
#SBATCH --mem=0
#SBATCH --partition=dcgp_usr_prod
#SBATCH -A uTS25_Tornator_0
#SBATCH -t 00:30:00
#SBATCH --exclusive

NODE_COUNTS=(1 2 4 8 16 32)
NODES=${NODE_COUNTS[$SLURM_ARRAY_TASK_ID]}
#SBATCH --nodes=${NODES}

# --- Config ---
EXEC=./stencil_parallel
ARGS="-x 25000 -y 25000 -n 100 -o 0"
RESULTS_FILE="mpi_scaling_${NODES}nodes.txt"

module load openMPI/5.0.5
make MODE=parallel LOG=0

export OMP_NUM_THREADS=${SLURM_CPUS_PER_TASK}
export OMP_PLACES=cores
export OMP_PROC_BIND=spread

echo ">>> Running on $NODES node(s) with 1 MPI rank per node"

mpirun -np $NODES \
       --map-by ppr:1:node \
       $EXEC $ARGS > output_${NODES}.log
