#!/bin/bash
#SBATCH --nodes=1                   # 1 node
#SBATCH --ntasks=12                  # total MPI tasks across nodes
#SBATCH --ntasks-per-node=12         # 4 MPI tasks on the node
#SBATCH --cpus-per-task=2           # 8 OpenMP threads per MPI task
#SBATCH --mem=0                     # use all available memory
#SBATCH --partition=THIN
#SBATCH -t 00:00:30                 # 5 minutes
#SBATCH --exclusive                 # Get exclusive access to benchmark
#SBATCH --job-name=stencil_test

# Set the executable name
EXEC=./stencil_parallel

# =======================================================
# Set OpenMP environment variables
export OMP_NUM_THREADS=${SLURM_CPUS_PER_TASK}
export OMP_PLACES=cores
export OMP_PROC_BIND=close

# Loading necessary module
module load openMPI/5.0.5

# Set the total number of MPI tasks
TOTAL_MPI_TASKS=${SLURM_NTASKS}

# Define the arguments for the executable
# A medium-sized grid suitable for a single-node run
ARGS="-x 5000 -y 5000 -n 100 -o 0"

# Print run information
echo "Running on a single node with ${TOTAL_MPI_TASKS} MPI tasks."
echo "Each task uses ${OMP_NUM_THREADS} OpenMP threads."

# Compiling with logging the serial version
make MODE=parallel LOG=0

# Run the code using mpirun
mpirun -np ${TOTAL_MPI_TASKS} ${EXEC} ${ARGS} > ${TOTAL_MPI_TASKS}_mpi_${OMP_NUM_THREADS}_threads.log
